version: '3'

services:
  database-mysql:
    container_name: database-mysql
    image: mysql/mysql-server:8.0
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=file
      - MYSQL_ROOT_PASSWORD=qweasdzxc123
      - MYSQL_USER=lmc
      - MYSQL_PASSWORD=qweasdzxc123
      - TZ=Asia/Seoul
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-init-files/:/docker-entrypoint-initdb.d/

  database-adminer:
    container_name: database-adminer
    image: adminer:latest
    ports:
      - "18080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=database-mysql
      - ADMINER_DESIGN=hydra
      - ADMINER_PLUGINS=tables-filter tinymce